Change naming
AY2324S2-CS2103T-T14-2/tp pull request #55
Opened 2024-03-26 12:18 UTC by Vision-2000

Following changes were made to variables, methods and comments in the main folder:

- Anything with "Person" changed to "Patient"
- Anything with "addressbook" changed to either of "patientlist" or "meditrack" depending on context of whether it is used to refer to app name or class name

Test folder not fully updated yet.

**There is a high risk that some things break, especially JSON related functionalities**

2024-03-28 09:01 UTC, jskimdev requested changes
Change the list to patient list in the comment sections

2024-03-28 11:25 UTC, jeong-jaeho reviewed
LGTM. It just needs some minor changes.

2024-03-28 11:25 UTC, jeong-jaeho commented on docs/tutorials/AddRemark.md
> +Simply add the following to [`seedu.address.ui.PatientCard`](https://github.com/se-edu/addressbook-level3/commit/850b78879582f38accb05dd20c245963c65ea599#diff-639834f1e05afe2276a86372adf0fe5f69314642
Nice change of class names, but it seems some classes still have Person instead of Patient. For instance, personListPanel and PersonCard.

2024-03-28 11:25 UTC, jeong-jaeho commented on src/main/java/seedu/address/logic/commands/DeleteByIndexCommand.java
> + * Deletes a patient identified using it's displayed index from the list
I agree with Junseo.  It would be better to call it patient list, since there will may be other lists added in the future.

2024-03-29 12:35 UTC, Vision-2000 commented on docs/tutorials/AddRemark.md
> +Simply add the following to [`seedu.address.ui.PatientCard`](https://github.com/se-edu/addressbook-level3/commit/850b78879582f38accb05dd20c245963c65ea599#diff-639834f1e05afe2276a86372adf0fe5f69314642
The scope of this name change is only for src/main folder. It would be too much effort to change the test folder (trust me I tried, intellij is not smart enough for this). As for docs, we have a week to finish documentation, that is where I will do a check. 

According to intellij search function (blame this piece of **** if it's wrong) there's only 1 trace of the word "person" in src/main, and its in the css stylesheet referencing some unknown element that I'm not sure if I can remove safely.

2024-03-29 12:56 UTC, Vision-2000 commented on src/main/java/seedu/address/logic/commands/DeleteAllCommand.java
> + * Deletes all entries in the list.
Made all changes

2024-03-31 08:01 UTC, merged